FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV VITE_API_BASE_URL=https://eventprolabs-ruleta-mvp-back.3haody.easypanel.host
ENV VITE_ADMIN_KEY=TU_CLAVE_ADMIN
ENV VITE_DEFAULT_EVENT_ID=1
ENV VITE_DASHBOARD_REFRESH_MS=5000

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80